module.exports = {
  projects: [
    '<rootDir>/apps/demos',
    '<rootDir>/apps/docs',
    '<rootDir>/apps/tour-of-heroes',
    '<rootDir>/apps/tour-of-heroes-ngxs',
    '<rootDir>/apps/vanilla-case-studies',
    '<rootDir>/libs/test-helpers',
    '<rootDir>/libs/state',
    '<rootDir>/libs/template',
    '<rootDir>/libs/cdk',
    '<rootDir>/libs/cdk/zone-configurations',
    '<rootDir>/libs/cdk/render-strategies',
    '<rootDir>/libs/cdk/template-management',
    '<rootDir>/libs/cdk/notifications',
    '<rootDir>/libs/cdk/coalescing',
    '<rootDir>/libs/cdk/coercing',
    '<rootDir>/libs/cdk/zone-less',
    '<rootDir>/libs/template/rx-let',
    '<rootDir>/libs/template/push',
  ],
};
