# This is just a 'ghost' workflow to have all the github CI passed
name: 'build'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  name: build
  build:
    runs-on: ubuntu-latest

    steps:
      run: echo Hello, world!
