name: CI/CD

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group on branch name (`refs/heads/main`)
  # - Is pull request? Group on pull request branch name, for example `feat/add-awesome-feature`
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.ref
        || github.head_ref
    }}
  # Run merge workflows in sequence to prevent parallel deployments and releases
  # Cancel stale pull request runs in progress for the same branch
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  # We're using Nx Cloud for Distributed Task Execution
  # Reference: https://nx.dev/using-nx/dte
  #
  # The coordinator outputs the combination of task outputs from the agents,
  # both terminal and file outputs
  dte_coordinator:
    name: DTE Coordinator
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      # Must match dte_agents.number-of-agents
      number-of-agents: 4
      # The --stop-agents-after parameter must match the task target listed last
      # in the parallel-commands-on-agents command list
      # The --agent-count parameter must match the number-of-agents parameter
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=4
      # Commands run in parallel in this DTE coordinator
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
      # Commands distributed between DTE agents
      # Distribution strategy for 2 vCPUs per hosted runner (GitHub Free):
      # lint: 2 tasks assigned at a time, 1 task per vCPU
      # test: 1 task assigned at a time with 2 parallel processes, 1 process per vCPU
      # build: 2 tasks assigned at a time, 1 task per vCPU
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=2 --max-parallel=2
        yarn nx affected --target=test --parallel=1 --max-parallel=1 --max-workers=2 --ci --code-coverage
        yarn nx affected --target=build --exclude=docs --parallel=2 --max-parallel=2

  dte_agents:
    name: DTE Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      # The Free GitHub plan has a limit of 20 concurrent jobs on Ubuntu images
      # Reference: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      # If we need to, we can optimize for 2 simultaneous workflow runs:
      # 2 x 1 main job   =  2 concurrent jobs
      # 2 x 9 agent jobs = 18 concurrent jobs
      # Total            = 20 concurrent jobs
      #
      # However, we don't have many projects or targets in this workspace, so we
      # lower the number of agents to reduce spent compute time.
      number-of-agents: 4
