# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build-docs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin master
      - run: npm install --frozen-lockfile --non-interactive
      - run: npm run build-docs-page
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'docs/*'
          force: true
          author_name: Github Action
          message: 'chore(docs): GitHub pages generation'
          # Whether to use the --force option on `git add`, in order to bypass eventual gitignores
          # Default: false
          #force: true
          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the workflow (from GITHUB_REF)
          ref: 'github-pages'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
